name: test workflow
on: push

jobs:
  build:
    name: Build test prog
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: run
      run: /bin/bash prog.sh
    
