name: test workflow
on: push

jobs:
  test:
    name: Test switch ip script
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: install nginx
      run: sudo apt-get install nginx
    - name: create upstream file
      run: touch upstream
    - name: run with existed domain
      run: python3 switch_ip.py google.com upstream swip.log
    - name: show result
      run: cat upstream
    - name: show log
      run: cat swip.log
    - name: run with changed ip
      run: python3 switch_ip.py google.co upstream swip.log
    - name: show result
      run: cat upstream
    - name: show log
      run: cat swip.log
    - name: run with not existed domain
      run: python3 switch_ip.py notexisted.comne upstream swip.log
    - name: show result
      run: cat upstream
    - name: show log
      run: cat swip.log
