name: test workflow
on: push

jobs:
  build:
    name: Test switch ip script
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: create upstream file
      run: touch upstream
    - name: run
      run: python3 switch_ip.py google.com upstream swip.log
    
